### ISSUE TITLE
[Bug]: App does not work on none-english windows versions

### ISSUE THREAD

**Issue by Wizkeezy** [svrooij/WingetIntune#16]
### Command

package

### Full command

winget-intune package JanDeDobbeleer.OhMyPosh --package-folder c:\packages

### App version

0.5.1+Branch.main.Sha.4e664f91572820bcb6b450bc5e155110b24bfa79

### What happened?

A issue/error happened!

### Relevant log output

```Shell
info: WingetIntune.Implementations.WingetManager[4] Getting package info for JanDeDobbeleer.OhMyPosh (null)
info: WingetIntune.Commands.PackageCommand[0] Package (null) (null) from Winget
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at WingetIntune.Implementations.WingetManager.GetPackageInfoAsync(String id, String version, String source, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/WingetManager.cs:line 50
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 78
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
If you run the command with `--verbose` behind, you should see which Winget command is executed. What happens if you run that yourself?

Something like `winget show --id JanDeDobbeleer.OhMyPosh`

My best guess is that this command fails as well or has a timeout.

**Comment by Wizkeezy** [comment]
Hi svrookij,

Firstable thanks for fast answer.

That the result of add --verbose to commanD
C:\Users\kfernandez>winget-intune package JanDeDobbeleer.OhMyPosh --package-folder c:\packages --verbose
info: WingetIntune.Implementations.WingetManager[4] Getting package info for JanDeDobbeleer.OhMyPosh (null)
dbug: WingetIntune.Os.ProcessManager[1] Running **winget show --id JanDeDobbeleer.OhMyPosh --exact --accept-source-agreements --disable-interactivity**
dbug: WingetIntune.Os.ProcessManager[2] Process exited with code 0.
info: WingetIntune.Commands.PackageCommand[0] Package (null) (null) from Winget
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at WingetIntune.Implementations.WingetManager.GetPackageInfoAsync(String id, String version, String source, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/WingetManager.cs:line 50
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 78
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   
   But the command **winget-intune package JanDeDobbeleer.OhMyPosh --package-folder c:\packages --verbose**  doesn´t fail as you can see:

C:\Users\kfernandez>winget show --id JanDeDobbeleer.OhMyPosh --exact --accept-source-agreements --disable-interactivity
Encontrado Oh My Posh [JanDeDobbeleer.OhMyPosh]
Versión: 18.7.0
Editor: Jan De Dobbeleer
Dirección URL del editor: https://github.com/JanDeDobbeleer/oh-my-posh/
Dirección URL de soporte del editor: https://github.com/JanDeDobbeleer/oh-my-posh/issues
Autor: Jan De Dobbeleer
Moniker: oh-my-posh
Descripción: Prompt theme engine for any shell
Página principal: https://ohmyposh.dev/
Licencia: MIT
Dirección URL de la licencia: https://github.com/JanDeDobbeleer/oh-my-posh/raw/main/COPYING
Dirección URL de notas de la versión: https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v18.7.0
Etiquetas:
  console
  command-line
  shell
  command-prompt
  powershell
  wsl
  developer-tools
  utilities
  cli
  cmd
  ps
  terminal
  oh-my-posh
Instalador:
  Tipo de instalador: inno
  Dirección URL del instalador: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v18.7.0/install-amd64.exe
  Instalador SHA256: 071ceebaafbfbce77352ab2752301aa51938f2601d112574bedbf58773dbda25
  Fecha de lanzamiento: 2023-09-04

Thanks a lot.

Regards.

**Comment by svrooij** [comment]
You see the problem here? My app calls Winget, and expects the output in English, but it translates the output in the users' language.

There was an issue, but it got closed... https://github.com/microsoft/winget-cli/issues/184
For now I guess you can skip the Winget part of you add the exact version with `--version 18.6.0` that should skip the Winget command looking for the latest version.

In the mean time I'm planning to remove the winget.exe dependency by looking into a rest api of sorts.

**Comment by Wizkeezy** [comment]
You mean, the version of app in winget repository?

like this (Now i try with Zoom for example):

C:\Users\kfernandez>**winget-intune package Zoom.Zoom --version 5.15.11.21032 --package-folder c:\packages**
info: WingetIntune.Implementations.WingetManager[4] Getting package info for Zoom.Zoom 5.15.11.21032
info: WingetIntune.Commands.PackageCommand[0] Package (null) (null) from Winget
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at WingetIntune.Implementations.WingetManager.GetPackageInfoAsync(String id, String version, String source, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/WingetManager.cs:line 50
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 78
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Same issue...

**Comment by svrooij** [comment]
According to the code it should skip the package manager if both the version and the source are specified.

https://github.com/svrooij/WingetIntune/blob/4e664f91572820bcb6b450bc5e155110b24bfa79/src/WingetIntune/Implementations/WingetManager.cs#L50-L58

So this code would package the app in the mean time:

```Shell
winget-intune package Zoom.Zoom --version 5.15.11.21032 --package-folder c:\packages --source winget
```

**Comment by Wizkeezy** [comment]
Understood and proved, nice. Thank you a lot

Regards.

**Comment by svrooij** [comment]
I would like to keep this issue open, I do need to find an issue to get it to work on none English machines....

**Comment by svrooij** [comment]
`dotnet tool update --global SvRooij.Winget-Intune.Cli --version 0.5.2 --no-cache`

And the tool should work on French machines as well!
