### ISSUE TITLE
[Bug]: Zoom.Zoom publishing failed

### ISSUE THREAD

**Issue by NateHutch365** [svrooij/WingetIntune#32]
### Command

publish

### Full command

wintuner publish Zoom.Zoom --package-folder C:\WinTuner

### App version

0.8.0-alpha.8+Branch.dev.Sha.bc5a5036712eb2e328599ac924c2bfecf53c9e6e.bc5a5036712eb2e328599ac924c2bfecf53c9e6e

### What happened?

Initially tried publishing with version 0.7.0 but it failed so tried the alpha version.

### Command output

```Shell
wintuner publish Zoom.Zoom --package-folder C:\WinTuner
info: WingetIntune.Commands.PackageCommand[0] Try loading latest version from package index
info: WingetIntune.Implementations.WingetManager[5] Getting package info for Zoom.Zoom 5.17.2.29988 from github
info: WingetIntune.Commands.PackageCommand[0] Publishing package Zoom.Zoom 5.17.2.29988
info: WingetIntune.IntuneManager[0] Created app 1426b790-b56f-475e-b811-329eda124190, starting with content
info: WingetIntune.Implementations.ChunkedAzureFileUploader[0] Uploading C:\Users\User\AppData\Local\Temp\8085e4f2-9bc5-4b5f-adda-d0ff0a9a0eed\IntuneWinPackage\Contents\IntunePackage.intunewin to https://mmcswdb01.blob.core.windows.net/c9496b1b-57d7-4290-89e5-dc89b3e1770d/8619e912-24e4-458e-bfb9-3361cff36603/8ae44211-f736-4f6c-8988-55415fe6b4ac.intunewin.bin?sv=2017-04-17&sr=b&si=-965810261&sig=8GjsC7i24MpZlBCgiBvlIM1mMc5vujQLwenXsqSJHGo%3D
fail: WingetIntune.Implementations.ChunkedAzureFileUploader[0] Failed to upload C:\Users\User\AppData\Local\Temp\8085e4f2-9bc5-4b5f-adda-d0ff0a9a0eed\IntuneWinPackage\Contents\IntunePackage.intunewin to https://mmcswdb01.blob.core.windows.net/c9496b1b-57d7-4290-89e5-dc89b3e1770d/8619e912-24e4-458e-bfb9-3361cff36603/8ae44211-f736-4f6c-8988-55415fe6b4ac.intunewin.bin?sv=2017-04-17&sr=b&si=-965810261&sig=8GjsC7i24MpZlBCgiBvlIM1mMc5vujQLwenXsqSJHGo%3D System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.  ---> System.TimeoutException: The operation was canceled.  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.  ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.  ---> System.IO.IOException: Unable to write data to the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.    --- End of inner exception stack trace ---    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|153_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)    at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)    at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)    at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)    --- End of inner exception stack trace ---    at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    --- End of inner exception stack trace ---    --- End of inner exception stack trace ---    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at WingetIntune.Implementations.ChunkedAzureFileUploader.UploadChunkAsync(String chunkId, Byte[] chunkData, Uri sasUri, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/ChunkedAzureFileUploader.cs:line 80    at WingetIntune.Implementations.ChunkedAzureFileUploader.UploadFileToAzureAsync(String filename, Uri sasUri, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/ChunkedAzureFileUploader.cs:line 55
fail: WingetIntune.IntuneManager[0] Error publishing app, deleting the remains System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.  ---> System.TimeoutException: The operation was canceled.  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.  ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.  ---> System.IO.IOException: Unable to write data to the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.    --- End of inner exception stack trace ---    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|153_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)    at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)    at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)    at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)    --- End of inner exception stack trace ---    at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    --- End of inner exception stack trace ---    --- End of inner exception stack trace ---    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at WingetIntune.Implementations.ChunkedAzureFileUploader.UploadChunkAsync(String chunkId, Byte[] chunkData, Uri sasUri, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/ChunkedAzureFileUploader.cs:line 80    at WingetIntune.Implementations.ChunkedAzureFileUploader.UploadFileToAzureAsync(String filename, Uri sasUri, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/ChunkedAzureFileUploader.cs:line 55    at WingetIntune.IntuneManager.AddContentVersionToApp(GraphServiceClient graphServiceClient, String appId, String intuneFilePath, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 341    at WingetIntune.IntuneManager.PublishAppAsync(String packagesFolder, PackageInfo packageInfo, IntunePublishOptions options, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 221
```

### Windows version and current language

Windows 11 Version 22H2 (OS Build 22621.3007)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by NateHutch365** [comment]
Curious to know as well, when publishing the app after the modern auth window I see the typical 'Do you want to allow your org to manage this device' window where I then uncheck the box and choose this app only - Is this supposed to happen and how would I clear that so I can sign into a different tenant?

**Comment by svrooij** [comment]
@NateHutch365 may I ask what your internet speed is? It's will upload the intunewin package in small chunks of `6MB` and (apparently) the default timeout for the HttpClient is 100 seconds. So for you it fails to complete with 1 of the chunks in those 100 seconds. Doing some quick calculations that means your upload speed is below 62 kilobyte per second.

For the other question please create a [discussion](https://github.com/svrooij/WingetIntune/discussions/categories/q-a) so the answer can also help others.

**Comment by NateHutch365** [comment]
Hey Stephen, see below

![image](https://github.com/svrooij/WingetIntune/assets/61209613/784037ab-6e27-434e-8b5c-10ed807fceec)

**Comment by svrooij** [comment]
So the upload speed is pretty low, I will however change the timeout to something higher. You can always try uploading the package through the portal in the mean time.

**Comment by NateHutch365** [comment]
Yep it's funny now that you mention it as even the manual upload of the intunewin file has been slow over the past few days and I wasn't sure why (roughly 20 mins to do 50MB) - I will speak to my provider and see what is going on. Will continue to test and let you know, thanks!

**Comment by svrooij** [comment]
@NateHutch365 I guess this issue can be closed? Could you re-open if the issue is not resolved?
