### ISSUE TITLE
[Bug]: No installer found for ShareX.ShareX 15.0.0 X64

### ISSUE THREAD

**Issue by anubis-genix** [svrooij/WingetIntune#35]
### Command

package

### Full command

wintuner package ShareX.ShareX --package-folder C:\WingetIntune

### App version

0.8.0-alpha.8+Branch.dev.Sha.bc5a5036712eb2e328599ac924c2bfecf53c9e6e.bc5a5036712eb2e328599ac924c2bfecf53c9e6e

### What happened?

First of all, thanks for the great app!
According to the Devs GitHub there is no specific x64 installer for this app.
https://github.com/ShareX/ShareX/releases/

### Command output

```Shell
PS C:\Users\WDAGUtilityAccount> wintuner package ShareX.ShareX --package-folder C:\WingetIntune
info: WingetIntune.Commands.PackageCommand[0] Getting latest version for ShareX.ShareX
info: WingetIntune.Implementations.WingetManager[5] Getting package info for ShareX.ShareX 15.0.0 from github
info: WingetIntune.Commands.PackageCommand[0] Package ShareX.ShareX 15.0.0 from Winget
Unhandled exception: System.ArgumentException: No installer found for ShareX.ShareX 15.0.0 X64
   at WingetIntune.IntuneManager.ComputeInstallerDetails(PackageInfo& package, PackageOptions packageOptions) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 554
   at WingetIntune.IntuneManager.GenerateInstallerPackage(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 89
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 88
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Windows version and current language

Windows 11 - English (Sandbox)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
The [ShareX manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/ShareX/ShareX/16.0.1/ShareX.ShareX.installer.yaml) says its installer is not architecture specific. You can package it with `wintuner package ShareX.ShareX --package-folder C:\Tools\packages\ --architecture Unknown`

In the meantime I'll create a fix for this issue as well.
