### ISSUE TITLE
[Bug]: Downloading installer failed because of buffer size

### ISSUE THREAD

**Issue by brandonall** [svrooij/WingetIntune#38]
### Command

package

### Full command

PS C:\Windows\system32> winget-intune package Bluebeam.Revu.21 --package-folder C:\Winget

### App version

0.7.0+Branch.main.Sha.6f15dab446ea9f234d069287d6ca0c3eadbc54be.6f15dab446ea9f234d069287d6ca0c3eadbc54be

### What happened?

PS C:\Windows\system32> winget-intune package Bluebeam.Revu.21 --package-folder C:\Winget
info: WingetIntune.Commands.PackageCommand[0] Getting latest version for Bluebeam.Revu.21
info: WingetIntune.Implementations.WingetManager[5] Getting package info for Bluebeam.Revu.21 21.0.50 from github
info: WingetIntune.Commands.PackageCommand[0] Package Bluebeam.Revu.21 21.0.50 from Winget
info: WingetIntune.IntuneManager[1] Generating IntuneWin package for Bluebeam.Revu.21 21.0.50 in C:\Winget
info: WingetIntune.IntuneManager[4] Downloading installer from https://downloads.bluebeam.com/software/downloads/21.0.50/BbRevu21.0.50.exe to C:\Users\Brandon\AppData\Local\Temp\intunewin\Bluebeam.Revu.21\21.0.50\BbRevu21.0.50.exe
Unhandled exception: System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WingetIntune.Os.DefaultFileManager.DownloadFileAsync(String url, String path, String expectedHash, Boolean throwOnFailure, Boolean overrideFile, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/DefaultFileManager.cs:line 58
   at WingetIntune.IntuneManager.DownloadInstallerAsync(String tempPackageFolder, PackageInfo packageInfo, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 484
   at WingetIntune.IntuneManager.GenerateNoneMsiInstaller(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 109
   at WingetIntune.IntuneManager.GenerateInstallerPackage(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 96
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 88
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

### Windows version and current language

Windows 10 - English

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@brandonall I'm curious, do you have any idea how big the installer actually is? The following line triggered me.

```
Unhandled exception: System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
```

Which seems to be the [default configuration](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.maxresponsecontentbuffersize?view=net-8.0).

**Comment by svrooij** [comment]
@brandonall I've tried packaging the app with the latest version (0.8.1] and it's now able to download the installer correctly. In the meantime the app became more memory friendly for everybody, by not loading a big download in the memory before saving to disk.

**Comment by brandonall** [comment]
Thank you so much. I really appreciate you looking into this. Your package
has been so helpful.

**Comment by svrooij** [comment]
Your welcome! You can also check out the just released [PowerShell module](https://wintuner.app/docs/category/wintuner-powershell), with the same functionality.

And if you want to show you gratitude 👉 [sponsor profile](https://github.com/sponsors/svrooij)

**Comment by brandonall** [comment]
I just tried running again and I get stuck here, did you notice an
unusually long time here or have I done something wrong?

**Comment by svrooij** [comment]
Ow yes, downloading 2.1GB took a long time. And there is no progress bar... Maybe I should try to build that.

Do you have any logs, at what point are you stuck?

**Comment by brandonall** [comment]
As I was reading your response it finished. I guess I was too impatient.
Everything downloaded properly.
