### ISSUE TITLE
[Bug]: Package Microsoft.SQLServerManagementStudio failed downloading

### ISSUE THREAD

**Issue by jannikk09** [svrooij/WingetIntune#44]
### Command

package

### Full command

wintuner package Microsoft.SQLServerManagementStudio --package-folder C:\WingetIntune

### App version

Got no output

### What happened?

Notepad++ was created successfully but SSMS doesen't work for me. 

### Command output

```Shell
Unhandled exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\runner\AppData\Local\Temp\intunewin\Microsoft.SQLServerManagementStudio\20.0' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at WingetIntune.Os.DefaultFileManager.DownloadFileAsync(String url, String path, String expectedHash, Boolean throwOnFailure, Boolean overrideFile, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Implementations/DefaultFileManager.cs:line 71
   at WingetIntune.IntuneManager.DownloadInstallerAsync(String tempPackageFolder, PackageInfo packageInfo, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 438
   at WingetIntune.IntuneManager.GenerateNoneMsiInstaller(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 112
   at WingetIntune.IntuneManager.GenerateInstallerPackage(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 99
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 88
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Windows version and current language

Windows 11 - German

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
@jannikk09 I see the same error, this has to do that this app tries to calculate the filename for the file from the url.. And Microsoft choose to no link directly to the download but to `https://go.microsoft.com/fwlink/?linkid=2264204&clcid=0x407` for which it cannot possibly calculate a filename.

**Comment by svrooij** [comment]
![image](https://github.com/svrooij/WingetIntune/assets/1292510/98c8a80d-ab54-44f2-94c4-27c420730cfa)
I might have found the issue, and build a fix for it 😄
