### ISSUE TITLE
[Bug]: CLI cannot login

### ISSUE THREAD

**Issue by wilso974** [svrooij/WingetIntune#47]
### Command

publish

### Full command

wintuner publish 7zip.7zip --package-folder C:\Users\Administrator\Desktop\vredist

### App version

0.8.3+5223c56ae709364a27c44196b5873379a8bac500

### What happened?

I can't sign in to microsoft

### Command output

```Shell
fail: WingetIntune.Graph.GraphAppUploader[0] Error publishing app, deleting the remains MSAL.NetCore.4.60.1.0.MsalClientException:                                                                                                                          ErrorCode: authentication_canceled Microsoft.Identity.Client.MsalClientException: User canceled authentication.     at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.SignInInteractivelyAsync(AuthenticationRequestParameters authenticationRequestParameters)    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.AcquireTokenInteractiveAsync(AuthenticationRequestParameters authenticationRequestParameters, AcquireTokenInteractiveParameters acquireTokenInteractiveParameters)    at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.FetchTokensAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync(String brokerInstallUrl, CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext() --- End of stack trace from previous location ---    at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)    at WingetIntune.Internal.Msal.PublicClientAuth.AcquireTokenInteractiveAsync(IEnumerable`1 scopes, String tenantId, String userId, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 120    at WingetIntune.Internal.Msal.PublicClientAuth.AccuireTokenAsync(IEnumerable`1 scopes, String tenantId, String userId, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 95    at WingetIntune.Internal.Msal.PublicClientAuth.AuthenticateRequestAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 130    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)    at Microsoft.Graph.Beta.DeviceAppManagement.MobileApps.MobileAppsRequestBuilder.PostAsync(MobileApp body, Action`1 requestConfiguration, CancellationToken cancellationToken)    at WingetIntune.Graph.MobileAppsRequestBuilderExtensions.PostAsync(MobileAppsRequestBuilder builder, Win32LobApp win32LobApp, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/MobileAppsRequestBuilderExtensions.cs:line 15    at WingetIntune.Graph.GraphAppUploader.CreateNewAppAsync(GraphServiceClient graphServiceClient, Win32LobApp win32LobApp, String intunePackageFile, String logoPath, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/GraphAppUploader.cs:line 49
```

### Windows version and current language

Windows 10 - French

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by wilso974** [comment]
Hello, thanx for your reply,

 the message is the next when i use the commande publish



fail: WingetIntune.Graph.GraphAppUploader[0] Error publishing app, deleting the remains MSAL.NetCore.4.60.1.0.MsalClientException:      ErrorCode: authentication_canceled Microsoft.Identity.Client.MsalClientException: User canceled authentication.     at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.SignInInteractivelyAsync(AuthenticationRequestParameters authenticationRequestParameters)    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.AcquireTokenInteractiveAsync(AuthenticationRequestParameters authenticationRequestParameters, AcquireTokenInteractiveParameters acquireTokenInteractiveParameters)    at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.FetchTokensAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync(String brokerInstallUrl, CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext() --- End of stack trace from previous location ---    at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)    at WingetIntune.Internal.Msal.PublicClientAuth.AcquireTokenInteractiveAsync(IEnumerable`1 scopes, String tenantId, String userId, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 120    at WingetIntune.Internal.Msal.PublicClientAuth.AccuireTokenAsync(IEnumerable`1 scopes, String tenantId, String userId, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 95    at WingetIntune.Internal.Msal.PublicClientAuth.AuthenticateRequestAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 130    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)    at Microsoft.Graph.Beta.DeviceAppManagement.MobileApps.MobileAppsRequestBuilder.PostAsync(MobileApp body, Action`1 requestConfiguration, CancellationToken cancellationToken)    at WingetIntune.Graph.MobileAppsRequestBuilderExtensions.PostAsync(MobileAppsRequestBuilder builder, Win32LobApp win32LobApp, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/MobileAppsRequestBuilderExtensions.cs:line 15    at WingetIntune.Graph.GraphAppUploader.CreateNewAppAsync(GraphServiceClient graphServiceClient, Win32LobApp win32LobApp, String intunePackageFile, String logoPath, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/GraphAppUploader.cs:line 49
Unhandled exception: MSAL.NetCore.4.60.1.0.MsalClientException:
        ErrorCode: authentication_canceled
Microsoft.Identity.Client.MsalClientException: User canceled authentication.
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.SignInInteractivelyAsync(AuthenticationRequestParameters authenticationRequestParameters)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.AcquireTokenInteractiveAsync(AuthenticationRequestParameters authenticationRequestParameters, AcquireTokenInteractiveParameters acquireTokenInteractiveParameters)
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.FetchTokensAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync(String brokerInstallUrl, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at WingetIntune.Internal.Msal.PublicClientAuth.AcquireTokenInteractiveAsync(IEnumerable`1 scopes, String tenantId, String userId, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 120
   at WingetIntune.Internal.Msal.PublicClientAuth.AccuireTokenAsync(IEnumerable`1 scopes, String tenantId, String userId, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 95
   at WingetIntune.Internal.Msal.PublicClientAuth.AuthenticateRequestAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Internal/Msal/PublicClientAuth.cs:line 130
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Beta.DeviceAppManagement.MobileApps.MobileAppsRequestBuilder.PostAsync(MobileApp body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at WingetIntune.Graph.MobileAppsRequestBuilderExtensions.PostAsync(MobileAppsRequestBuilder builder, Win32LobApp win32LobApp, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/MobileAppsRequestBuilderExtensions.cs:line 15
   at WingetIntune.Graph.GraphAppUploader.CreateNewAppAsync(GraphServiceClient graphServiceClient, Win32LobApp win32LobApp, String intunePackageFile, String logoPath, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/GraphAppUploader.cs:line 49
   at WingetIntune.Graph.GraphAppUploader.CreateNewAppAsync(GraphServiceClient graphServiceClient, Win32LobApp win32LobApp, String intunePackageFile, String logoPath, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Graph/GraphAppUploader.cs:line 82
   at WingetIntune.IntuneManager.PublishAppAsync(String packagesFolder, PackageInfo packageInfo, IntunePublishOptions options, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 206
   at WingetIntune.Commands.PublishCommand.HandleCommand(PublishCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PublishCommand.cs:line 105
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext

**Comment by wilso974** [comment]
![error command publish](https://github.com/svrooij/WingetIntune/assets/166653304/1df2338d-6238-4202-85f3-652727e595a6)

**Comment by svrooij** [comment]
Did you try to login with your work account that has access to Intune? Does your tenant have Intune licenses? Did you get an error after you entered your credentials?

The error message says you "cancelled" the login screen.

**Comment by wilso974** [comment]
Thank you for your help, I use my tenant id and it's work.

Thank you for your reactivity.

Best Regards
