### ISSUE TITLE
[Bug]: NullReference exception packaging Insomnia

### ISSUE THREAD

**Issue by svrooij** [svrooij/WingetIntune#6]
### Command

package

### Full command

winget-intune package Insomnia.Insomnia --package-folder c:\tools\packages\

### App version

0.3.0+Branch.main.Sha.3d80560d99d6de494e0a440555e2458fa6a1139a

### What happened?

System.NullReferenceException: Object reference not set to an instance of an object.

### Relevant log output

```Shell
winget-intune package Insomnia.Insomnia --package-folder c:\tools\packages\
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\stephan
info: WingetIntune.WingetManager[4]
      Getting package info for Insomnia.Insomnia (null)
info: WingetIntune.Os.ProcessManager[1]
      Running winget show --id Insomnia.Insomnia --exact --accept-source-agreements --disable-interactivity
info: WingetIntune.Os.ProcessManager[2]
      Process exited with code 0.

info: WingetIntune.Commands.PackageCommand[0]
      Package Insomnia.Insomnia 2023.5.3 from Winget
info: System.Net.Http.HttpClient.IFileManager.LogicalHandler[100]
      Start processing HTTP request GET https://github.com/microsoft/winget-pkgs/raw/master/manifests/i/Insomnia/Insomnia/2023.5.3/Insomnia.Insomnia.yaml
info: System.Net.Http.HttpClient.IFileManager.ClientHandler[100]
      Sending HTTP request GET https://github.com/microsoft/winget-pkgs/raw/master/manifests/i/Insomnia/Insomnia/2023.5.3/Insomnia.Insomnia.yaml
info: System.Net.Http.HttpClient.IFileManager.ClientHandler[101]
      Received HTTP response headers after 459.9306ms - 200
info: System.Net.Http.HttpClient.IFileManager.LogicalHandler[101]
      End processing HTTP request after 465.2393ms - 200
info: System.Net.Http.HttpClient.IFileManager.LogicalHandler[100]
      Start processing HTTP request GET https://github.com/microsoft/winget-pkgs/raw/master/manifests/i/Insomnia/Insomnia/2023.5.3/Insomnia.Insomnia.installer.yaml
info: System.Net.Http.HttpClient.IFileManager.ClientHandler[100]
      Sending HTTP request GET https://github.com/microsoft/winget-pkgs/raw/master/manifests/i/Insomnia/Insomnia/2023.5.3/Insomnia.Insomnia.installer.yaml
info: System.Net.Http.HttpClient.IFileManager.ClientHandler[101]
      Received HTTP response headers after 364.9767ms - 200
info: System.Net.Http.HttpClient.IFileManager.LogicalHandler[101]
      End processing HTTP request after 365.081ms - 200
info: System.Net.Http.HttpClient.IFileManager.LogicalHandler[100]
      Start processing HTTP request GET https://github.com/microsoft/winget-pkgs/raw/master/manifests/i/Insomnia/Insomnia/2023.5.3/Insomnia.Insomnia.locale.en-US.yaml
info: System.Net.Http.HttpClient.IFileManager.ClientHandler[100]
      Sending HTTP request GET https://github.com/microsoft/winget-pkgs/raw/master/manifests/i/Insomnia/Insomnia/2023.5.3/Insomnia.Insomnia.locale.en-US.yaml
info: System.Net.Http.HttpClient.IFileManager.ClientHandler[101]
      Received HTTP response headers after 371.2481ms - 200
info: System.Net.Http.HttpClient.IFileManager.LogicalHandler[101]
      End processing HTTP request after 371.3323ms - 200
info: WingetIntune.IntuneManager[1]
      Generating IntuneWin package for Insomnia.Insomnia 2023.5.3 in c:\tools\packages\
info: WingetIntune.IntuneManager[3]
      Downloading content prep tool from https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/raw/master/IntuneWinAppUtil.exe
info: WingetIntune.Os.DefaultFileManager[0]
      Skipping download of https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/raw/master/IntuneWinAppUtil.exe to C:\Users\stephan\AppData\Local\Temp\intunewin\IntuneWinAppUtil.exe because the file already exists
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WingetIntune.IntuneManager.GenerateNoneMsiInstaller(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 89
   at WingetIntune.IntuneManager.GenerateInstallerPackage(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 73
   at WingetIntune.Commands.PackageCommand.HandleCommand(PackageCommandOptions options, InvocationContext context) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune.Cli/Commands/PackageCommand.cs:line 68
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
This got fixed in #9 by using an alternative installer when x64 is not available
