### ISSUE TITLE
[Bug]: PowerShell Deploy fails with "Value cannot be null. (Parameter 's')" (mac only)

### ISSUE THREAD

**Issue by holnburger** [svrooij/WingetIntune#79]
### CommandLet

Deploy-WtWin32App

### Full command

Deploy-WtWin32App -PackageFolder "/Users/josef/Intune/Zoom.Zoom/6.0.39959" -Username info@example.com

### Module version

0.8.8

### What happened?

Some deploys fail, apparently because there is a parameter missing in the app.json.

It happened with the following packages:

Zoom.Zoom
KeePassXCTeam.KeePassXC
Google.Chrome

I used a pipe deploy: New-WtWingetPackage -PackageId "Zoom.Zoom" -PackageFolder "/Users/josef/Intune" | Deploy-WtWin32App -Username "info@example.com" 
(but it also happened with downloading it first and deploying it with a path to the folder)

### Command output

```PowerShell
INFO: [IntuneManager] Writing detection info with msi details Google.Chrome {829B647D-A3F1-39D5-B446-9D7EC9AB5705}
INFO: [IntuneManager] Writing package readme for package Google.Chrome
INFO: Loading package details from folder /Users/josef/Intune/Google.Chrome/126.0.6478.57
Deploy-WtWin32App: Value cannot be null. (Parameter 's')
```

### PowerShell version

7.4.2 (on a Mac)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I won't demand an immediate answer

**Comment by svrooij** [comment]
I think it cannot handle the file path, not sure how I can check what happens.

What happens if you add `-Debug -Verbose`? I'm hoping that will add some logging to the output window.

**Comment by holnburger** [comment]
Sure:

```PS /Users/josef/Intune> New-WtWingetPackage -PackageId "Google.Chrome" -PackageFolder "/Users/josef/Intune" | Deploy-WtWin32App -Username "redacted@redacted.com" -Debug -Verbose
INFO: Packaging package Google.Chrome 126.0.6478.57
INFO: [WingetManager] Getting package info for Google.Chrome 126.0.6478.57 from github
INFO: [IntuneManager] Generating IntuneWin package for Google.Chrome 126.0.6478.57 X64 System in /Users/josef/Intune
INFO: [IntuneManager] Downloading installer from https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi to /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi
WARNING: [IntuneManager] Unable to get product code from /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi because Microsoft.Deployment.WindowsInstaller.dll is not available on Linux
INFO: [Packager] Creating Intune package from /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57
INFO: [Packager] Creating package for /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi in /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57 to /Users/josef/Intune/Google.Chrome/126.0.6478.57
INFO: [Packager] Compressing the source folder /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57 to /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/1550d387-3ece-40e4-ab4c-62aa5e193d8d/IntuneWinPackage/Contents/IntunePackage.intunewin
INFO: [Packager] Generating application info
INFO: [Packager] Encrypting file /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/1550d387-3ece-40e4-ab4c-62aa5e193d8d/IntuneWinPackage/Contents/IntunePackage.intunewin
INFO: [Packager] Generated detection XML file /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/1550d387-3ece-40e4-ab4c-62aa5e193d8d/IntuneWinPackage/Metadata/Detection.xml
INFO: [Packager] Done creating package for /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi in /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57 to /Users/josef/Intune/Google.Chrome/126.0.6478.57
INFO: [IntuneManager] Downloading logo from https://api.winstall.app/icons/Google.Chrome.png
INFO: [DefaultFileManager] Skipping download of https://api.winstall.app/icons/Google.Chrome.png to /Users/josef/Intune/Google.Chrome/logo.png because the file already exists
INFO: [IntuneManager] Writing detection info with msi details Google.Chrome {829B647D-A3F1-39D5-B446-9D7EC9AB5705}
INFO: [IntuneManager] Writing package readme for package Google.Chrome
INFO: Loading package details from folder /Users/josef/Intune/Google.Chrome/126.0.6478.57
Deploy-WtWin32App: Value cannot be null. (Parameter 's')```


Maybe this is the issue? WARNING: [IntuneManager] Unable to get product code from /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi because Microsoft.Deployment.WindowsInstaller.dll is not available on Linux

I'm using a mac.

**Comment by svrooij** [comment]
Thanks!

No the packaging is fine, just thinking that it does not load the info from the folder.
Will add some more logging in the next version, to further debug what is happening.

The 'issue' that it's it not loading the details is expected. That prevents it from crashing.

**Comment by svrooij** [comment]
@holnburger can you have another try with version `0.8.9` and the debug switches, while it did not mention this is the release notes I added some logging to the deploy part to diagnose this problem.

**Comment by holnburger** [comment]
This is the output

```
PS /Users/josef/Intune> New-WtWingetPackage -PackageId "Google.Chrome" -PackageFolder "/Users/josef/Intune" | Deploy-WtWin32App -Username "redacted@redacted.com" -Debug -Verbose
INFO: [WingetRepository] Loading package index from https://raw.githubusercontent.com/svrooij/winget-pkgs-index/main/index.json
INFO: [WingetRepository] Saving package index to cache at /Users/josef/Library/Application Support/WingetCommunityRepo/index.json
INFO: Packaging package Google.Chrome 126.0.6478.57
INFO: [WingetManager] Getting package info for Google.Chrome 126.0.6478.57 from github
INFO: [IntuneManager] Generating IntuneWin package for Google.Chrome 126.0.6478.57 X64 System in /Users/josef/Intune
INFO: [IntuneManager] Downloading installer from https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi to /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi
WARNING: [IntuneManager] Unable to get product code from /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi because Microsoft.Deployment.WindowsInstaller.dll is not available on Linux
INFO: [Packager] Creating Intune package from /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57
INFO: [Packager] Creating package for /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi in /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57 to /Users/josef/Intune/Google.Chrome/126.0.6478.57
INFO: [Packager] Compressing the source folder /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57 to /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/16886554-3c3e-40b4-86c2-6d45be3ec016/IntuneWinPackage/Contents/IntunePackage.intunewin
INFO: [Packager] Generating application info
INFO: [Packager] Encrypting file /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/16886554-3c3e-40b4-86c2-6d45be3ec016/IntuneWinPackage/Contents/IntunePackage.intunewin
INFO: [Packager] Generated detection XML file /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/16886554-3c3e-40b4-86c2-6d45be3ec016/IntuneWinPackage/Metadata/Detection.xml
INFO: [Packager] Done creating package for /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57/googlechromestandaloneenterprise64.msi in /var/folders/db/w7kxcbqx6mb6zltd2h_0hn1c0000gn/T/wintuner/Google.Chrome/126.0.6478.57 to /Users/josef/Intune/Google.Chrome/126.0.6478.57
INFO: [IntuneManager] Downloading logo from https://api.winstall.app/icons/Google.Chrome.png
INFO: [DefaultFileManager] Skipping download of https://api.winstall.app/icons/Google.Chrome.png to /Users/josef/Intune/Google.Chrome/logo.png because the file already exists
INFO: [IntuneManager] Writing detection info with msi details Google.Chrome {829B647D-A3F1-39D5-B446-9D7EC9AB5705}
INFO: [IntuneManager] Writing package readme for package Google.Chrome
INFO: Loading package details from folder /Users/josef/Intune/Google.Chrome/126.0.6478.57
Deploy-WtWin32App: Value cannot be null. (Parameter 's')
PS /Users/josef/Intune> Get-InstalledModule -Name WinTuner

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
0.8.9                WinTuner                            PSGallery            Package and publish any apps from WinGet to Intune.
```

The only difference in the logging seems to be:

```
INFO: [WingetRepository] Loading package index from https://raw.githubusercontent.com/svrooij/winget-pkgs-index/main/index.json
INFO: [WingetRepository] Saving package index to cache at /Users/josef/Library/Application Support/WingetCommunityRepo/index.json
```

**Comment by svrooij** [comment]
This happens every 3 hours:
```plain
INFO: [WingetRepository] Loading package index from https://raw.githubusercontent.com/svrooij/winget-pkgs-index/main/index.json
INFO: [WingetRepository] Saving package index to cache at /Users/josef/Library/Application Support/WingetCommunityRepo/index.json
```
You probably had it loaded already.

The problem is that there is something `null`, that shouldn't be, but the exception doesn't show which parameter.

This line:
```
INFO: Loading package details from folder /Users/josef/Intune/Google.Chrome/126.0.6478.57
```
comes from [this code](https://github.com/svrooij/WingetIntune/blob/main/src/Svrooij.WinTuner.CmdLets/Commands/DeployWtWin32App.cs#L155) on the next line there is an exclamation sign `!` which checks if the metadataManager is `null` (which it isn't suppose to).

If I check locally with a new fake program, it would tell me what object is null:
![image](https://github.com/svrooij/WingetIntune/assets/1292510/082b0502-4324-4c9f-b6f7-9f0a4e104689)

## Conclusion

This issue is hidden somewhere else, not sure how to find this without a mac available

**Comment by holnburger** [comment]
Happy to help with a live session if you have time for that. Completely understand if you don’t. Sadly can’t send you a Mac tough ;)

**Comment by svrooij** [comment]
I stumbled upon the same issue when running this on Linux....
![image](https://github.com/user-attachments/assets/e756828c-f776-42af-85f5-667e45b7b4d1)

I think I can research it on Linux as well, still puzzled by this issue

**Comment by miyoyo** [comment]
I just found out you can use $Error[0] after the command crashes to get the CLR exception object, so you can do `$Error[0].Exception.StackTrace` to get the stack trace.

```
   at System.ArgumentNullException.Throw(String paramName)
   at System.Text.Encoding.GetBytes(String s)
   at WingetIntune.Models.Mapper.ToWin32LobApp(PackageInfo packageInfo) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Models/Mapper.cs:line 78
   at WingetIntune.IntuneManager.WritePackageInfo(String packageFolder, PackageInfo packageInfo, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 572
   at WingetIntune.IntuneManager.GenerateMsiPackage(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 76
   at WingetIntune.IntuneManager.GenerateInstallerPackage(String tempFolder, String outputFolder, PackageInfo packageInfo, PackageOptions packageOptions, CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/WingetIntune/Intune/IntuneManager.cs:line 116
   at Svrooij.WinTuner.CmdLets.Commands.NewWtWingetPackage.ProcessRecordAsync(CancellationToken cancellationToken) in /home/runner/work/WingetIntune/WingetIntune/src/Svrooij.WinTuner.CmdLets/Commands/NewWtWingetPackage.cs:line 180
   at Svrooij.PowerShell.DependencyInjection.Extensions.ThreadAffinitiveSynchronizationContext.RunSynchronized(Func`1 asyncOperation)
   at Svrooij.PowerShell.DependencyInjection.DependencyCmdlet`1.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

https://github.com/svrooij/WingetIntune/blob/main/src/WingetIntune/Models/Mapper.cs#L82 seems to be where the crash actually happens.

My best guess is that the package has no detection script/never has it's detection script set, and by putting a null assert combined with a decode, you get this error.

**Comment by svrooij** [comment]
@miyoyo  This has been a great help, we finally might be able to solve this.
